name: 🔖 Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: 🔖 Release
    runs-on: ubuntu-latest
    steps:
      - uses: fell-lucas/setup-pnpm-action@main
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          createGithubReleases: true
          publish: pnpm changeset publish
          version: pnpm changeset version
          commit: "chore(release): 🔖 publish"
          title: "chore(release): 🔖 publish"
